### ISSUE TITLE
Bug: Problem with my customizable character and errors when changing gf or opponent

### ISSUE THREAD

**Issue by Polo9876** [AbnormalPoof/FunkerSelector#1]
### Version

0.4.1

### Issue Checklist

- [x] Have you checked the Issues/Discussions to see if this hasn't been reported yet?
- [X] Have you tried reinstalling the mod?
- [X] Is this a genuine issue with Funker Selector and not a side-effect of another mod you have installed?

### Context (Provide images, videos, etc.)

Hello, I have two problems with this mod being:

1) When I add and change my customizable character, the game reads it as a default character, what should I do?

https://github.com/user-attachments/assets/3262a940-abf9-46fc-88de-282bc0607db6

2)When I want to change gf or opponent I get some errors that won't let me change

![Captura de pantalla (919)](https://github.com/user-attachments/assets/03c3f432-fb49-46ff-82b3-69b674b20947)
![Captura de pantalla (920)](https://github.com/user-attachments/assets/a28d4f62-2496-4f5b-b592-8cbf2dd28f74)
![Captura de pantalla (921)](https://github.com/user-attachments/assets/bbcc01a0-3584-4fde-9345-a423ba265a8f)
![Captura de pantalla (922)](https://github.com/user-attachments/assets/b865c6eb-cc9f-43a5-a10e-223fae93ec44)
![Captura de pantalla (923)](https://github.com/user-attachments/assets/5b54e9bb-99a4-492e-bf4c-f8abcbbb5233)
![Captura de pantalla (924)](https://github.com/user-attachments/assets/89435b26-55d3-40cd-a8d4-7c5036949b2e)

**Comment by AbnormalPoof** [comment]
Your character ID isn't `default` by any chance, is it?

**Comment by Polo9876** [comment]
no, it's not

**Comment by AbnormalPoof** [comment]
I think I understand the issue now. For some reason, `loadCharacter()` randomly throws a null object reference at times (this is used to use the Face icon on default). I have a fix on the repo.

In `scripts/states/CharacterMenu.hxc`, replace all instances of `loadCharacter('face')` with `configure('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')`

(Also, it's intentional for the Character Menu to start on Default!)

**Comment by Polo9876** [comment]
The 2nd problem was solved, but the 1st problem is still not solved, it is that my character, which as you saw in the recording was "polo-player", reads it to me as a default character

**Comment by AbnormalPoof** [comment]
The character will not change if one of these conditions are met:

- The stage does not exist
- The song is played through Story Mode
- The song is played through the Chart Editor
- The current character is the exact same as the character defined by the song chart.

Would it be okay for me to take a look at the character in question? (As in: Sending the files over)

**Comment by Polo9876** [comment]
here are the character files

[Polo-player.json](https://github.com/user-attachments/files/16568385/Polo-player.json)
[polo-player.json](https://github.com/user-attachments/files/16568386/polo-player.json)

**Comment by AbnormalPoof** [comment]
Judging from the JSON files alone, the character should function. I also see that you're using a custom song in the MP4, does the character work in other songs (preferably base game)?

**Comment by Polo9876** [comment]
I tried Darnel's song, Thorns Erect and Blammed but it comes out as a default character, like Pico and Boyfriend.

**Comment by AbnormalPoof** [comment]
Please try using the character without any other mods other than Funker Selector and whichever mod has the character.

**Comment by Polo9876** [comment]
I went to the chart editor and if he read me the character and I played with him with the song spokeez erect

**Comment by AbnormalPoof** [comment]
I can't really seem to figure out the issue.

**Comment by Polo9876** [comment]
I did it, I was able to find the problem was that in the JSON of the character (that is, where the pose data is) I had the name with a capital P and I put it in lower case

**Comment by Polo9876** [comment]
But now I have another problem, it is that when I add and change gf I get these errors
![Captura de pantalla (925)](https://github.com/user-attachments/assets/d4564200-9781-45d5-b55e-988ed51b6e0b)
![Captura de pantalla (926)](https://github.com/user-attachments/assets/8f21695c-0d8b-4f5c-a9a8-7fa47a5bf612)
![Captura de pantalla (927)](https://github.com/user-attachments/assets/fd1eebbd-452c-47ee-b0fc-4d97e5ac2053)

**Comment by AbnormalPoof** [comment]
This dictates an issue with the character's JSON file in `characters/`, Funker Selector looks for the `"name"` and `"assetPath"` properties.

**Comment by Polo9876** [comment]
I found the solution, thank you very much, sorry for the inconvenience.
