### ISSUE TITLE
Bug: Invalid char 34 at position 245

### ISSUE THREAD

**Issue by Polo9876** [AbnormalPoof/FunkerSelector#2]
### Version

0.4.1

### Issue Checklist

- [X] Have you checked the Issues/Discussions to see if this hasn't been reported yet?
- [X] Have you tried reinstalling the mod?
- [X] Is this a genuine issue with Funker Selector and not a side-effect of another mod you have installed?

### Context (Provide images, videos, etc.)

Hello, sorry for the inconvenience but, I added a new character and I got an error 

![Captura de pantalla (928)](https://github.com/user-attachments/assets/030f5d39-bfa8-4f71-81e5-771c462eca43)

here are the files for you to have a look at

[scorbunny-player.json](https://github.com/user-attachments/files/16576367/scorbunny-player.json)
[scorbunny-player.json](https://github.com/user-attachments/files/16576368/scorbunny-player.json)

**Comment by AbnormalPoof** [comment]
This is a syntax error, you didn't add a comma after `scale` in `characterMenu`:

```json
  "characterMenu":
  {
    "position": [170, 265],
    "scale": 1.2     <-- Here
    "selectedAnim": "cheer"
  }
```
