### ISSUE TITLE
Bug: No Pico Mixes

### ISSUE THREAD

**Issue by wik5000** [AbnormalPoof/FunkerSelector#7]
### Version

0.5.1 (The Latest Version)

### Issue Checklist

- [X] Have you checked the Issues/Discussions to see if this hasn't been reported yet?
- [ ] Have you tried reinstalling the mod?
- [ ] Have you tried disabling every mod except Funker Selector?
- [ ] Have you tried reproducing this issue on a fresh install of FNF?

### Context (Provide images, videos, etc.)

There Are No Pico Mixes Expect Weekend 1 Which Isn't Really One, Also There Is No Darnell BF Mix

**Comment by AbnormalPoof** [comment]
Not a bug with Funker Selector. This is a base game bug.
